POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Per Persson",
    "number": "123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test4",
    "number": "1212"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "fred",
    "number": "321"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "a11231",
    "number": ""
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "hello",
    "number": "040-12345"
}